### ISSUE TITLE
Diagnóstico de los activos de información (bancos de datos) digitales de información de SACMEX, SEDEMA y SGIRPC respecto a los indicadores prototipo.

### ISSUE THREAD

**Issue by iaga** [lancis-apc/cdmx#27]
## Actividades:

- [ ] Elaborar el inventario de activos de información disponible SACMEX, SEDEMA y SGIRPC https://github.com/lancis-apc/cdmx/issues/14
- [ ] Diseñar protocolo de gestión de activos de información con base en los entornos computacionales de software libre GeoNetwork, Lizmap, Sphinx, Python-Qgis https://github.com/lancis-apc/cdmx/issues/15
- [ ] Resumir el estado de los activos de información disponibles en SACMEX, SEDEMA y SGIRPC para identificar las prioridades en cuanto a los cursos de acción dirigidos a subsanar posibles deficiencias, omisiones y errores https://github.com/lancis-apc/cdmx/issues/16
